# [shell]
# program = 'pwsh'
# args = [
# "-noexit",
# "-c",
# "$vsPath = 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community'; Import-Module (Join-Path $vsPath 'Common7\\Tools\\Microsoft.VisualStudio.DevShell.dll'); Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation -DevCmdArguments '-arch=x64 -host_arch=x64'",
# ]

[cursor]
style = "Block"

[font]
size = 12
[font.normal]
family = "Sarasa Term Slab CL"

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
# padding = { x = 3, y = 3 }
dynamic_padding = true
dynamic_title = false
resize_increments = true
startup_mode = "Maximized"

[keyboard]
bindings = [
  { action = "ToggleFullscreen", key = "F11" },
]
