;;; fuz-bin-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from fuz-bin.el

(autoload 'fuz-bin-load-dyn "fuz-bin" "\
Load dynamic module. Optional QUIET argument to disable load message.

(fn &optional QUIET)" t)
(register-definition-prefixes "fuz-bin" '("fuz-bin-"))

;;; End of scraped data

(provide 'fuz-bin-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; fuz-bin-autoloads.el ends here
