;;; fzf-native-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from fzf-native.el

(autoload 'fzf-native-module-compile "fzf-native" "\
Compile fzf-native-module." t)
(autoload 'fzf-native-load-dyn "fzf-native" "\
Load dynamic module." t)
(autoload 'fzf-native-load-own-build-dyn "fzf-native" "\
Loads user-compiled version of module, building it if necessary")
(register-definition-prefixes "fzf-native" '("fzf-native-"))

;;; End of scraped data

(provide 'fzf-native-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; fzf-native-autoloads.el ends here
